"""Security utilities including encryption and secure file handling."""

from sandiraksa.security.hardening import (
    DEFAULT_CONFIG,
    FileSizeError,
    FileTypeError,
    SecurityConfig,
    SecurityError,
    XMLSecurityError,
    ZipBombError,
    check_zip_bomb,
    create_secure_xml_parser,
    parse_xml_safely,
    sanitize_filename,
    secure_file_operation,
    validate_file_path,
    validate_input_text,
)
from sandiraksa.security.crypto import (
    CRYPTO_VERSION,
    KEY_SIZE,
    NONCE_SIZE,
    CryptoEngine,
    CryptoError,
    DecryptionError,
    EncryptedData,
    EncryptionError,
    KeyDerivationError,
    compute_hmac,
    compute_hmac_hex,
    derive_key,
    generate_key,
    hash_bytes,
    hash_file,
    secure_compare,
)
from sandiraksa.security.key_store import (
    KeyManager,
    KeyNotFoundError,
    KeyStore,
    KeyStoreError,
    KeyStoreStatus,
    KeyStoreUnavailableError,
    OSKeyStore,
    PasswordDerivedKeyStore,
    get_key_manager,
    reset_key_manager,
)
from sandiraksa.security.vault import (
    AADContext,
    ProjectVault,
    VaultError,
    VaultLockedError,
    VaultManager,
    get_project_vault,
    get_vault_manager,
    reset_vault_manager,
)

__all__ = [
    # Crypto constants
    "CRYPTO_VERSION",
    "KEY_SIZE",
    "NONCE_SIZE",
    # Crypto classes
    "CryptoEngine",
    "EncryptedData",
    # Crypto functions
    "generate_key",
    "derive_key",
    "compute_hmac",
    "compute_hmac_hex",
    "secure_compare",
    "hash_bytes",
    "hash_file",
    # Crypto errors
    "CryptoError",
    "EncryptionError",
    "DecryptionError",
    "KeyDerivationError",
    # Key store
    "KeyStore",
    "OSKeyStore",
    "PasswordDerivedKeyStore",
    "KeyManager",
    "KeyStoreStatus",
    "KeyStoreError",
    "KeyNotFoundError",
    "KeyStoreUnavailableError",
    "get_key_manager",
    "reset_key_manager",
    # Vault
    "AADContext",
    "ProjectVault",
    "VaultManager",
    "VaultError",
    "VaultLockedError",
    "get_vault_manager",
    "get_project_vault",
    "reset_vault_manager",
    # Hardening
    "SecurityError",
    "XMLSecurityError",
    "ZipBombError",
    "FileSizeError",
    "FileTypeError",
    "SecurityConfig",
    "DEFAULT_CONFIG",
    "validate_file_path",
    "check_zip_bomb",
    "create_secure_xml_parser",
    "parse_xml_safely",
    "sanitize_filename",
    "validate_input_text",
    "secure_file_operation",
]
