"""Document handlers for various file formats."""

from sandiraksa.documents.csv_handler import (
    CSVCell,
    CSVHandler,
    CSVHandlerError,
    CSVMetadata,
    CSVReader,
    CSVWriter,
    DelimiterDetector,
    DelimiterError,
    EncodingDetector,
    EncodingError,
)
from sandiraksa.documents.docx_handler import (
    DOCXHandler,
    DOCXHandlerError,
    DOCXMetadata,
    DOCXReader,
    DOCXWriter,
    DocumentInventory,
    DocumentModificationError,
    DocumentOpenError,
    ParagraphInfo,
    TextRun,
    TextSpan,
)
from sandiraksa.documents.pptx_handler import (
    PPTXHandler,
    PPTXHandlerError,
    PPTXMetadata,
    PPTXReader,
    PPTXWriter,
    PresentationInventory,
    PresentationOpenError,
    ShapeInfo,
    SlideInventory,
    SlideModificationError,
    SlideNotesInfo,
    TableCellInfo,
)
from sandiraksa.documents.xlsx_handler import (
    CellModificationError,
    SheetInventory,
    WorkbookInventory,
    WorkbookOpenError,
    WorksheetError,
    XLSXCell,
    XLSXHandler,
    XLSXHandlerError,
    XLSXMetadata,
    XLSXReader,
    XLSXWriter,
)

__all__ = [
    # CSV Handler
    "CSVHandler",
    "CSVReader",
    "CSVWriter",
    "CSVMetadata",
    "CSVCell",
    "CSVHandlerError",
    "EncodingError",
    "DelimiterError",
    # Detectors
    "EncodingDetector",
    "DelimiterDetector",
    # XLSX Handler
    "XLSXHandler",
    "XLSXReader",
    "XLSXWriter",
    "XLSXMetadata",
    "XLSXCell",
    "XLSXHandlerError",
    "WorkbookOpenError",
    "WorksheetError",
    "CellModificationError",
    "SheetInventory",
    "WorkbookInventory",
    # DOCX Handler
    "DOCXHandler",
    "DOCXReader",
    "DOCXWriter",
    "DOCXMetadata",
    "DOCXHandlerError",
    "DocumentOpenError",
    "DocumentModificationError",
    "ParagraphInfo",
    "TextRun",
    "TextSpan",
    "DocumentInventory",
    # PPTX Handler
    "PPTXHandler",
    "PPTXReader",
    "PPTXWriter",
    "PPTXMetadata",
    "PPTXHandlerError",
    "PresentationOpenError",
    "SlideModificationError",
    "ShapeInfo",
    "TableCellInfo",
    "SlideNotesInfo",
    "SlideInventory",
    "PresentationInventory",
]
